bt_navigator:
  ros__parameters:
    navigators: ["navigate_to_pose", "navigate_through_poses"]   
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    transform_tolerance: 0.2
    wait_for_service_timeout: 2000
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator" 
      enable_groot_monitoring: false
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator" 
      enable_groot_monitoring: false


controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0 

    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"  

      primary_controller: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController" 

      angular_dist_threshold: 0.785  
      rotate_to_heading_angular_vel: 0.8 

      rotate_to_goal_heading: true
      goal_yaw_tolerance: 0.25 

      desired_linear_vel: 0.25
      max_linear_accel: 0.4
      max_angular_accel: 1.0
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9

      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785   # rad (~45deg) da cambiare 
      rotate_to_heading_angular_vel: 0.8


planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlanner2D"
      tolerance: 0.25
      downsample_costmap: false
      allow_unknown: true
      max_planning_time: 2.0
      cost_travel_multiplier: 2.0

behavior_server:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.2
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_footprint
      transform_tolerance: 0.3
      update_frequency: 5.0
      publish_frequency: 5.0
      resolution: 0.05
      origin_x: 0.0
      origin_y: 0.0
      rolling_window: false


      robot_radius: 0.22

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/map"
        subscribe_to_updates: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: "/scan"
          max_obstacle_height: 1.5
          clearing: true
          marking: true
          inf_is_valid: false
          expected_update_rate: 1.0     
          observation_persistence: 0.0  
          transform_tolerance: 0.2
          raytrace_max_range: 2.0
          obstacle_max_range: 2.0


      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
        cost_scaling_factor: 3.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_footprint
      transform_tolerance: 0.3
      update_frequency: 10.0
      publish_frequency: 10.0
      resolution: 0.1
      width: 10
      height: 10
      rolling_window: true

      robot_radius: 0.22

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: "/scan"
          max_obstacle_height: 1.5
          clearing: true
          marking: true
          inf_is_valid: false

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.25
        cost_scaling_factor: 4.0

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    loop_rate: 20
    stop_on_failure: false

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ['controller_server', 'planner_server', 'behavior_server', 'bt_navigator', 'waypoint_follower']
    bond_timeout: 10.0
    bond_respawn_max_duration: 20.0
    attempt_respawn_reconnection: true
