[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "redis_image_codec"
version = "0.1.0"
dependencies = [
    "numpy",
    "opencv-python",
    "msgpack",
    "lz4",
]

[tool.setuptools.packages.find]
where = ["."]
