bt_navigator:
  ros__parameters:
    navigators: ["navigate_to_pose", "navigate_through_poses"]   # per docs
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    transform_tolerance: 0.2
    wait_for_service_timeout: 2000
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator" 
      enable_groot_monitoring: false
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator" # In Iron and older versions, "/" was used instead of "::"
      enable_groot_monitoring: false


controller_server:
  ros__parameters:
    allow_reversing: false
    use_sim_time: false
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false

      # Robot kinematics (tune to match your AI2-THOR motion)
      min_vel_x: 0.0
      max_vel_x: 0.4
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.4
      min_speed_theta: 0.0

      acc_lim_x: 0.4
      acc_lim_y: 0.0
      acc_lim_theta: 1.0

      # Critic plugins and weights (good starting point)
      critics:
        - RotateToGoal
        - Oscillation
        - BaseObstacle
        - GoalAlign
        - PathAlign
        - PathDist
        - GoalDist
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlanner2D"
      tolerance: 0.125
      downsample_costmap: false
      allow_unknown: true
      max_planning_time: 2.0
      cost_travel_multiplier: 2.0

behavior_server:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.2
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_footprint
      transform_tolerance: 0.3
      update_frequency: 5.0
      publish_frequency: 1.0
      resolution: 0.05
      origin_x: 0.0
      origin_y: 0.0
      rolling_window: false


      # controlla che sia ok (ai2thor default dice che ha forma di capsula)
      robot_radius: 0.22

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/map"
        subscribe_to_updates: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: "/scan"
          max_obstacle_height: 1.9
          clearing: true
          marking: true
          inf_is_valid: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
        cost_scaling_factor: 3.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_footprint
      transform_tolerance: 0.3
      update_frequency: 10.0
      publish_frequency: 10.0
      resolution: 0.05
      width: 10
      height: 10
      rolling_window: true

      robot_radius: 0.22

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: "/scan"
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          inf_is_valid: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
        cost_scaling_factor: 3.0

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    loop_rate: 20
    stop_on_failure: false

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ['controller_server', 'planner_server', 'behavior_server', 'bt_navigator', 'waypoint_follower']
    bond_timeout: 10.0
    bond_respawn_max_duration: 20.0
    attempt_respawn_reconnection: true
